### ISSUE TITLE
Split the different charts in their respective branches

### ISSUE THREAD

**Issue by jmesnil** [jbossas/eap-charts#28]
Right now, all Helm Charts (eap74, eap-xp3) are developed in the `main` branch.

This is not suitable for maintenance as it is difficult to track which commits affect one or the other charts (that have different lifecycle).

Instead, each chart should be maintained in its own branch (`eap74`, `eap-xp3`).
They would still all be made available from https://jbossas.github.io/eap-charts/.

The release workflow would have to change: for all maintained branches, we will use the Helm Chart Releaser action to release a new chart every time a chart version is updated.

During maintenance, we would contribute PR to fix issues as usual.
The last step before release will be the update of the Chart version to trigger the release of the new Helm Chart.

Actions:

- EAP 7.4
  - [x] create `eap74` and `eap74-dev` branches
  - [x] copy the chart and examples for the eap74 branch into the eap74 branch (and keep the history)
  - [x] delete the chart and examples for the eap74 from the `main` branch
- [x] EAP XP 3 and XP 4
  - [x] nothing to do, they will stay on `main`
- [x] EAP 8
  - [x] create a `eap8` and `eap8-dev` branch
- [x] update the helm.yaml GH action to run it against any branch (other than `gh-pages` and `*-dev` ones)

**Comment by spriadka** [comment]
@jmesnil I see lots of actions items on the list are already done, can this issue be updated?/What are the plans for the future?

**Comment by jmesnil** [comment]
@spriadka thanks for the bump, I've updated the checklist. The only outstanding issue is to remove the eap74 code from the `main` branch

**Comment by jmesnil** [comment]
thanks to @soul2zimate, the issue is completed.
