### ISSUE TITLE
Env configuration for resource quota/limit are ignored

### ISSUE THREAD

**Issue by whitingjr** [jbossas/eap-charts#46]
**Describe the bug**
None of the container platform resources are configured with any limit/quota.

**To Reproduce**

$ helm install eapfoo --debug -f app.yaml -f values.yaml -n default --repo https://jbossas.github.io/eap-charts eap-xp4

Please include if possible the debug output to get the values provided to the chart with 

Here we can see the deployer configured with cpu 2000m.

```
$ helm install eapfoo --debug -f app.yaml -f values.yaml -n default --repo https://jbossas.github.io/eap-charts eap-xp4 |grep -B 5 cpu
install.go:194: [debug] Original chart version: ""
install.go:211: [debug] CHART PATH: /home/whitingjr/.cache/helm/repository/eap-xp4-1.0.0.tgz

client.go:133: [debug] creating 8 resource(s)
  uri: https://github.com/hpehl/first-responder-demo.git
deploy:
  containers:
  - resources:
      requests:
        cpu: 2000m
--
  - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
    value: frdemo-kafka:9092
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
--
  uri: https://github.com/hpehl/first-responder-demo.git
deploy:
  containers:
  - resources:
      requests:
        cpu: 2000m
--
      port: admin
    initialDelaySeconds: 60
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu

```

**Expected behavior**
At least one resource with a cpu 2000m limit.

**Component Versions(please complete the following information):**

```
$ helm version
version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.19.6"}
$ oc version
Client Version: 4.12.0-202304070941.p0.g31aa3e8.assembly.stream-31aa3e8
Kustomize Version: v4.5.7
Server Version: 4.10.43
Kubernetes Version: v1.23.12+8a6bfe4
$
```
 
**Additional context**

**Comment by jmesnil** [comment]
@whitingjr just to be sure, the `app.yaml` you showed is not properly indented. Is it the actual YAML you are using or was it a copy/paste issue when you created the gist?

**Comment by whitingjr** [comment]
Great advice and thank you for the pointers.
 Yes these are good candidates for RFEs.

**Comment by whitingjr** [comment]
@jmesnil I created #50 . Is this the RFE candidate you had in mind ?
