### ISSUE TITLE
Invalid link on the helm-charts website

### ISSUE THREAD

**Issue by TomasHofman** [jbossas/eap-charts#67]
1. Go to https://jbossas.github.io/eap-charts/.
2. At the very bottom of the page, click on the documentation link in the "A complete documentation of the eap7 Chart is available in its README." sentence.
3. You get 404.

**Comment by jmesnil** [comment]
@TomasHofman thanks for the report, I fixed the link

**Comment by TomasHofman** [comment]
Super fast, thanks @jmesnil :).
