### ISSUE TITLE
Update the Helm Chart repository to highlight EAP 8

### ISSUE THREAD

**Issue by bstansberry** [jbossas/eap-charts#69]
**Describe the bug**
https://jbossas.github.io/eap-charts/ only mentions EAP 7.4

**Expected behavior**
EAP 8 should be listed, and before 7.4

**Comment by jmesnil** [comment]
@bstansberry thanks, I've updated the home page. The `helm search repo eap` lists all charts in alphanumerical order so EAP 8 is last. I've also added a section specific to EAP 8 installation
